### ISSUE TITLE
Missing firmware

### ISSUE THREAD

**Issue by nemanjan00** [ElectronicCats/faultycat#2]
Hello,
According to sales page, there should be firmware in this repo. 
Can you tell me if firmware is public and if yes, where can I download it?

I have seen that there are binary blobs in releases, but, I also expected source code

**Comment by Eric286** [comment]
Hello @nemanjan00

Thank you for being so interested in our firmware!

The firmware section is now active and accessible to all users.

You can find the firmware [here](https://github.com/ElectronicCats/faultycat/tree/main/firmware).

Best Regards,
Support Team.

**Comment by nemanjan00** [comment]
Thanks!
