### ISSUE TITLE
Details on differences from PicoEMP

### ISSUE THREAD

**Issue by mrx23dot** [ElectronicCats/faultycat#4]
From current description it's not clear enough what are the benefits compared to PicoEMP:

 (1) safe operation, (2) high performance, (3) usability, and finally (4) cost. 

e.g. how pulse is different.

Also how it's optimized for cost when price is 2x of PicoEMP

**Comment by xpeqex** [comment]
Hi @mrx23dot 

Thank you for the feedback. While FaultyCat is based on PicoEMP we were looking on improving the product itself. 

In any case, I agree that more information should be added to better clarify the improvements in FaultyCat. 

Here is a short description to the points you are mentioning that will be later updated in the wiki:
1. **_Safe operation_**. This refers to the use of commands to remotely operate FaultyCat, the enclosure that protects the user from a discharge of high-power components and the automatic shutdown function.
2. **_High Performance_**. Unlike other EMFI tools, FultyCat allows you to trigger the EMFI with a shorter charging time, using only three AA batteries and with a high voltage output through the _business end_, around 200V according to our tests.
3. **_Usability_** . FaultyCat **is a plug and play device, no need to solder and with firmware preloaded**. In any case, we work to provide further documentation and support. So you do not have only a product but a service too backing FaultyCat.
4. **_Cost_** . It is important to highlight the performance of FaultyCat against other EMFI device and the fact we take care of all the details of the board, from the manufacture process, testing to the provide support.

With this being said, FaultyCat as PicoEMP is an open source project, meaning that anyone can use the available information to improve and/or modify the product itself creating a more specialized product that fits your needs.

Hope this information is helpful. Be assure we will add this to our documentation, thank you for brining it to our attention.

Feel free to share with us any other feedback or queries!
